### ISSUE TITLE
correct datatype and blocksize is not loaded

### ISSUE THREAD

**Issue by haehn** [Rhoana/butterfly2#3]
whenever a new datasource is initialized, the datatype and blocksize should be determined and used when serving the data

**Comment by thejohnhoffer** [comment]
Resolved in PR #5

**Comment by thejohnhoffer** [comment]
[Fixed in merge for PR 5][0]

[0]: https://github.com/Rhoana/butterfly2/commit/764b029b55bf09bc3c176faf99c0420f11bd64b4
