### ISSUE TITLE
limit cache

### ISSUE THREAD

**Issue by haehn** [Rhoana/butterfly2#4]
use a LRU cache and set a max

**Comment by thejohnhoffer** [comment]
So basically `Settings/settings.py` defines two things.
- `MAX_CACHE_SIZE` defaults to 1GiB (1,073,741,824 bytes). This sets a cap on the sum memory usage of all in `[[tile for tile in entry._tiles] for entry in server._core._cache._sources]`
- `MAX_CACHE_ENTRY` is now hardcoded at `10`. This sets a cap on `len(server._core._cache._sources)`

- Both `_cache._sources` and `entry._tiles` are `lrucache` dictionaries.
    - The size of the `_cache._sources` at most at `MAX_CACHE_ENTRY`
    - The size of each `entry._tiles` is set based on the size of `_cache._sources`
        - Each `entry in _cache._sources` has an equal portion of `MAX_CACHE_SIZE`
            - __each `len(entry._tiles)` max is given by datatype and blocksize of `entry.query`__

### For example
- I cache ONE `_cache._sources`, 
    - Its path ends with _segmentation.h5_
        - A tile is `4(bytes)*1*1000*1000(px)` = `4000000(bytes/tile)`
        - This entry has`1073741824(bytes) / 1(entry) = 1073741824(bytes)`
        - This entry can have `1073741824(bytes)/4000000(bytes/tile) = 268(tiles)`

- I cache TWO `_cache._sources`, 
    - The first path still ends with _segmentation.h5_
        - A tile is `4(bytes)*1*1000*1000(px)` = `4000000(bytes/tile)`
        - This entry has`1073741824(bytes) / 2(entries) = 536870912(bytes)`
        - This entry can have `1073741824(bytes)/4000000(bytes/tile) = 134(tiles)`
    - The second path ends with _image.h5_
        - A tile is `1(bytes)*1*1000*1000(px)` = `1000000(bytes/tile)`
        - This entry has`1073741824(bytes) / 2(entries) = 536870912(bytes)`
        - This entry can have `536870912(bytes)/1000000(bytes/tile) = 536(tiles)`

So one segmentation cache can have 134 tiles. If there's a segmentation cache and an image cache, they each get the same total storage. So the segmentation cache gets only 134 tiles while the image cache gets 536 tiles.

You can see the result of both examples logged on lines 1-2 and 6-8 below. 
```
INFO:root:Starting /home/harvard/2017/data/bf/self/0/ecs/segmentation.h5 cache
INFO:root:Total 1 entries in cache
INFO:root:Entry /home/harvard/2017/data/bf/self/0/ecs/segmentation.h5 can have 268 entries
INFO:root:Adding [ 1  8  8 40  0  0] to /home/harvard/2017/data/bf/self/0/ecs/segmentation.h5 cache
INFO:tornado.access:200 GET /api/data?sample=0&experiment=self&dataset=ecs&channel=segmentation.h5&x=100&y=100&z=40&width=10&height=100&resolution=3 (66.31.19.46) 13.13ms
INFO:root:Starting /home/harvard/2017/data/bf/self/0/ecs/image.h5 cache
INFO:root:Total 2 entries in cache
INFO:root:Entry /home/harvard/2017/data/bf/self/0/ecs/image.h5 can have 536 entries
INFO:root:Entry /home/harvard/2017/data/bf/self/0/ecs/segmentation.h5 can have 134 entries
INFO:root:Adding [ 1  8  8 40  0  0] to /home/harvard/2017/data/bf/self/0/ecs/image.h5 cache
INFO:tornado.access:304 GET /api/data?sample=0&experiment=self&dataset=ecs&channel=image.h5&x=100&y=100&z=40&width=10&height=100&resolution=3 (66.31.19.46) 9.36ms
```
