### ISSUE TITLE
Channel_metadata only returns from rh_config

### ISSUE THREAD

**Issue by thejohnhoffer** [Rhoana/butterfly2#7]
For `/api/data` requests, the `block-size` and the `data-type` are defined by looking at the data.

For `/api/channel_metadata` requests, the `dimensions` and the `data-type` are defined by looking at the rh_config.

These should really be consistent. I think it's better to look directly at the data for `dimensions` and `data-type`, since it makes writing rh_config files easier (two fields can be omitted). Plus, it always guarantees the results are accurate so long as the relevant `Datasource` implements a `preload_source` method.

We should apply the same approach from #5 to `api/channel_metadata`. We should make a dummy tile request to call `TileQuery.preload_source.` on the first channel_metadata request if the source isn't already in the cache.

**Comment by LeeKamentsky** [comment]
I think I disagree here. I feel much more comfortable having an explicit
specification of the data type and feel some discomfort at having to look
at the actual data, especially to determine the dimensions. If you need a
use case, we might have an HDF5 file that encompasses a large volume, but
have a cutout that is annotated and the dimensions in rh_config limit the
volume to that portion of the data. The same HDF5 file might even be
specified in two different datasets to be used for two different purposes.

Also, it does feel a little heavy-handed and indirect to load a tile to
determine a constant or two.
